### ISSUE TITLE
Docs: Where to find plugin output in GitHub UI?

### ISSUE THREAD

**Issue by jtotoole** [utgwkk/pytest-github-actions-annotate-failures#26]
Hi all, thanks for the great work on this! I'm attempting to use the plugin in a project, and I think I've [implemented](https://github.com/mediacloud/backend/actions/runs/534727480) it correctly, but I'm not sure where I should expect to find the output that appears in the screenshot.

**Comment by utgwkk** [comment]
I took the screenshot in "Files changed" tab of a pull request. You can also see annotation messages in a summary page of actions if this plugin is enabled.

Is the test running in a docker container? This plugin is enabled when [`GITHUB_ACTIONS` environment variable](https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#default-environment-variables) is `true`, so you have to propagate `GITHUB_ACTIONS` variable to a container in the workflow. https://github.com/utgwkk/pytest-github-actions-annotate-failures/blob/c5ce22e2091f37ffb21ffcf254c77fe56640208a/pytest_github_actions_annotate_failures/plugin.py#L25-L28

**Comment by jtotoole** [comment]
I'll try that—thx a bunch!
