### ISSUE TITLE
Python 2 support

### ISSUE THREAD

**Issue by henryiii** [utgwkk/pytest-github-actions-annotate-failures#9]
I hate asking this, but if I can get it working, I'd like to use this for several large repositories, like pybind11, that won't be dropping Python 2 for a while. Plus PyTest 4.x supports Python 2, and GitHub Actions supports it as well. If there could be at least one Python2 compatible release, then you could use python_requires to make sure this doesn't (incorrectly) install on Python 2 on future Python 3 only releases (if you want to do that), that would be great!

**Comment by utgwkk** [comment]
I fixed this plugin to support Python 2.7 and pytest 4.x with #10, please wait for a new release! :pray:

**Comment by utgwkk** [comment]
@henryiii I've released [v0.0.7](https://pypi.org/project/pytest-github-actions-annotate-failures/0.0.7/) that is compatible with Python 2.7 (pytest 4.x.x).
